// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmhxbcywfjpmfusuvugg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtaHhiY3l3ZmpwbWZ1c3V2dWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTUyODcsImV4cCI6MjA2MDk5MTI4N30.ur6_uUDM5ws54JLSwbRxOpDl159EqdhVxWk256Je828";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);